import type { User } from "@/shared/types"

export const MOCK_USERS: User[] = [
  {
    id: "current-user",
    name: "You",
    avatar: "👤",
    stats: {
      completed: 11,
      ongoing: 4,
      totalMinutes: 1449,
      avgAccuracy: 91,
      xp: 2180,
      level: 5,
      streak: 7,
    },
    isFriend: false,
    isCurrentUser: true,
  },
  {
    id: "user-1",
    name: "Alex Chen",
    avatar: "🧑‍💻",
    stats: {
      completed: 15,
      ongoing: 3,
      totalMinutes: 1820,
      avgAccuracy: 94,
      xp: 2650,
      level: 6,
      streak: 12,
    },
    isFriend: true,
  },
  {
    id: "user-2",
    name: "Maria Garcia",
    avatar: "👩‍💼",
    stats: {
      completed: 8,
      ongoing: 5,
      totalMinutes: 1120,
      avgAccuracy: 88,
      xp: 1680,
      level: 4,
      streak: 5,
    },
    isFriend: true,
  },
  {
    id: "user-3",
    name: "James Wilson",
    avatar: "🧔",
    stats: {
      completed: 12,
      ongoing: 2,
      totalMinutes: 1580,
      avgAccuracy: 92,
      xp: 2240,
      level: 5,
      streak: 9,
    },
    isFriend: true,
  },
  {
    id: "user-4",
    name: "Sophie Taylor",
    avatar: "👩‍🎓",
    stats: {
      completed: 20,
      ongoing: 6,
      totalMinutes: 2450,
      avgAccuracy: 96,
      xp: 3420,
      level: 7,
      streak: 15,
    },
    isFriend: true,
  },
  {
    id: "user-5",
    name: "David Kim",
    avatar: "👨‍🔬",
    stats: {
      completed: 6,
      ongoing: 3,
      totalMinutes: 890,
      avgAccuracy: 85,
      xp: 1340,
      level: 3,
      streak: 3,
    },
    isFriend: true,
  },
]
