import type { Course, RoadmapItem } from "@/shared/types"

const generateSessions = (count: number, status: "completed" | "ongoing" | "recommended") => {
  if (status === "recommended") return []

  const sessions = []
  const now = Date.now()
  const dayInMs = 24 * 60 * 60 * 1000

  for (let i = 0; i < count; i++) {
    const startedAt = now - (count - i) * dayInMs * 2
    const minutes = Math.floor(Math.random() * 90) + 30
    const totalTasks = Math.floor(Math.random() * 15) + 5
    const completedTasks = status === "completed" ? totalTasks : Math.floor(totalTasks * (0.6 + Math.random() * 0.4))

    sessions.push({
      id: `session-${i}`,
      startedAt,
      endedAt: startedAt + minutes * 60 * 1000,
      minutes,
      completedTasks,
      totalTasks,
    })
  }

  return sessions
}

const generateRoadmap = (courseId: string, itemCount: number): RoadmapItem[] => {
  const roadmapTemplates: Record<string, string[]> = {
    default: ["Introduction", "Core Concepts", "Practical Examples", "Advanced Topics", "Final Project"],
  }

  const templates = roadmapTemplates.default
  const items: RoadmapItem[] = []

  for (let i = 0; i < Math.min(itemCount, templates.length); i++) {
    items.push({
      id: `${courseId}-roadmap-${i}`,
      title: templates[i],
      description: `Learn ${templates[i].toLowerCase()} in this module`,
      estimatedHours: Math.floor(Math.random() * 5) + 2,
      order: i,
    })
  }

  return items
}

const generateCourseDates = (status: "completed" | "ongoing" | "recommended", sessionCount: number) => {
  const now = Date.now()
  const dayInMs = 24 * 60 * 60 * 1000

  if (status === "recommended") {
    return { startDate: undefined, endDate: undefined }
  }

  if (status === "completed") {
    const endDate = now - dayInMs * 5
    const startDate = endDate - sessionCount * dayInMs * 2
    return { startDate, endDate }
  }

  if (status === "ongoing") {
    const startDate = now - sessionCount * dayInMs * 2
    const endDate = now + sessionCount * dayInMs * 1.5
    return { startDate, endDate }
  }

  return { startDate: undefined, endDate: undefined }
}

export const MOCK_COURSES: Course[] = [
  {
    id: "fe-1",
    title: "HTML & CSS Fundamentals",
    category: "Frontend",
    status: "completed",
    sessions: generateSessions(8, "completed"),
    performance: { accuracyPct: 95, pace: 8.5, totalTasksCompleted: 120, totalTasksAttempted: 126 },
    prereqIds: [],
    description: "Master the basics of web development",
    totalProgress: 100,
    roadmap: generateRoadmap("fe-1", 5),
    ...generateCourseDates("completed", 8),
  },
  {
    id: "fe-2",
    title: "JavaScript ES6+",
    category: "Frontend",
    status: "completed",
    sessions: generateSessions(12, "completed"),
    performance: { accuracyPct: 88, pace: 7.2, totalTasksCompleted: 156, totalTasksAttempted: 177 },
    prereqIds: ["fe-1"],
    description: "Modern JavaScript features and patterns",
    totalProgress: 100,
    roadmap: generateRoadmap("fe-2", 5),
    ...generateCourseDates("completed", 12),
  },
  {
    id: "fe-3",
    title: "React Fundamentals",
    category: "Frontend",
    status: "completed",
    sessions: generateSessions(10, "completed"),
    performance: { accuracyPct: 91, pace: 6.8, totalTasksCompleted: 98, totalTasksAttempted: 108 },
    prereqIds: ["fe-2"],
    description: "Build modern UIs with React",
    totalProgress: 100,
    roadmap: generateRoadmap("fe-3", 5),
    ...generateCourseDates("completed", 10),
  },
  {
    id: "fe-4",
    title: "Advanced React Patterns",
    category: "Frontend",
    status: "ongoing",
    sessions: generateSessions(6, "ongoing"),
    performance: { accuracyPct: 89, pace: 6.5, totalTasksCompleted: 45, totalTasksAttempted: 51 },
    prereqIds: ["fe-3"],
    description: "Hooks, Context, and advanced patterns",
    totalProgress: 65,
    roadmap: generateRoadmap("fe-4", 5),
    ...generateCourseDates("ongoing", 6),
  },
  {
    id: "fe-5",
    title: "TypeScript for React",
    category: "Frontend",
    status: "ongoing",
    sessions: generateSessions(4, "ongoing"),
    performance: { accuracyPct: 92, pace: 7.1, totalTasksCompleted: 32, totalTasksAttempted: 35 },
    prereqIds: ["fe-3"],
    description: "Type-safe React applications",
    totalProgress: 45,
  },
  {
    id: "fe-6",
    title: "Next.js App Router",
    category: "Frontend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["fe-4"],
    recommendedScore: 95,
    recommendationReason:
      "You've mastered React! Next.js is the natural next step for building production-ready full-stack applications.",
    unlockedCourseIds: ["be-6", "do-3"],
    description: "Full-stack React framework",
    totalProgress: 0,
  },
  {
    id: "fe-7",
    title: "CSS-in-JS & Styling",
    category: "Frontend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["fe-3"],
    recommendedScore: 78,
    recommendationReason:
      "Based on your CSS skills, learn modern styling solutions like styled-components and Emotion.",
    unlockedCourseIds: ["fe-6"],
    description: "Modern styling approaches",
    totalProgress: 0,
  },
  {
    id: "fe-8",
    title: "React Testing Library",
    category: "Frontend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["fe-4"],
    recommendedScore: 88,
    recommendationReason: "Your React skills are strong! Add testing to write more reliable and maintainable code.",
    unlockedCourseIds: ["do-3", "mb-7"],
    description: "Test React components effectively",
    totalProgress: 0,
  },
  {
    id: "fe-9",
    title: "State Management (Redux)",
    category: "Frontend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["fe-4"],
    recommendedScore: 72,
    recommendationReason: "Scale your React apps with Redux for complex state management in large applications.",
    unlockedCourseIds: ["fe-6"],
    description: "Manage complex application state",
    totalProgress: 0,
  },

  {
    id: "be-1",
    title: "Node.js Fundamentals",
    category: "Backend",
    status: "completed",
    sessions: generateSessions(10, "completed"),
    performance: { accuracyPct: 93, pace: 7.8, totalTasksCompleted: 115, totalTasksAttempted: 124 },
    prereqIds: ["fe-2"],
    description: "Server-side JavaScript",
    totalProgress: 100,
  },
  {
    id: "be-2",
    title: "Express.js & REST APIs",
    category: "Backend",
    status: "completed",
    sessions: generateSessions(8, "completed"),
    performance: { accuracyPct: 90, pace: 7.2, totalTasksCompleted: 87, totalTasksAttempted: 97 },
    prereqIds: ["be-1"],
    description: "Build RESTful web services",
    totalProgress: 100,
  },
  {
    id: "be-3",
    title: "Database Design (SQL)",
    category: "Backend",
    status: "ongoing",
    sessions: generateSessions(5, "ongoing"),
    performance: { accuracyPct: 87, pace: 6.9, totalTasksCompleted: 38, totalTasksAttempted: 44 },
    prereqIds: ["be-1"],
    description: "Relational database fundamentals",
    totalProgress: 58,
  },
  {
    id: "be-4",
    title: "MongoDB & NoSQL",
    category: "Backend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2"],
    recommendedScore: 85,
    recommendationReason: "You know Express! Learn NoSQL databases to build flexible, scalable backend systems.",
    unlockedCourseIds: ["be-7", "ds-9"],
    description: "Document-based databases",
    totalProgress: 0,
  },
  {
    id: "be-5",
    title: "GraphQL APIs",
    category: "Backend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2"],
    recommendedScore: 79,
    recommendationReason: "Upgrade from REST to GraphQL for more efficient and flexible API design.",
    unlockedCourseIds: ["fe-6", "be-7"],
    description: "Modern API design with GraphQL",
    totalProgress: 0,
  },
  {
    id: "be-6",
    title: "Authentication & Security",
    category: "Backend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2"],
    recommendedScore: 92,
    recommendationReason: "Critical skill! Learn JWT, OAuth, and security best practices to protect your applications.",
    unlockedCourseIds: ["do-9", "be-7"],
    description: "Secure your applications",
    totalProgress: 0,
  },
  {
    id: "be-7",
    title: "Microservices Architecture",
    category: "Backend",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2", "be-3", "be-4"],
    description: "Distributed system design",
    totalProgress: 0,
  },
  {
    id: "be-8",
    title: "Message Queues & Redis",
    category: "Backend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2"],
    recommendedScore: 74,
    recommendationReason: "Build async, scalable systems with message queues and in-memory caching.",
    unlockedCourseIds: ["be-7", "be-9"],
    description: "Async communication patterns",
    totalProgress: 0,
  },
  {
    id: "be-9",
    title: "API Performance & Caching",
    category: "Backend",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["be-2"],
    recommendedScore: 81,
    recommendationReason: "Make your APIs lightning fast with caching strategies and performance optimization.",
    unlockedCourseIds: ["do-7", "be-7"],
    description: "Optimize API performance",
    totalProgress: 0,
  },

  {
    id: "do-1",
    title: "Git & Version Control",
    category: "DevOps",
    status: "completed",
    sessions: generateSessions(6, "completed"),
    performance: { accuracyPct: 97, pace: 9.2, totalTasksCompleted: 78, totalTasksAttempted: 80 },
    prereqIds: [],
    description: "Master version control",
    totalProgress: 100,
  },
  {
    id: "do-2",
    title: "Docker Containers",
    category: "DevOps",
    status: "ongoing",
    sessions: generateSessions(4, "ongoing"),
    performance: { accuracyPct: 85, pace: 6.3, totalTasksCompleted: 28, totalTasksAttempted: 33 },
    prereqIds: ["do-1"],
    description: "Containerize your applications",
    totalProgress: 42,
  },
  {
    id: "do-3",
    title: "CI/CD Pipelines",
    category: "DevOps",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-1"],
    recommendedScore: 90,
    recommendationReason: "You know Git! Automate your workflow with CI/CD pipelines for faster, safer deployments.",
    unlockedCourseIds: ["do-6", "do-5"],
    description: "Automate your deployments",
    totalProgress: 0,
  },
  {
    id: "do-4",
    title: "Kubernetes Basics",
    category: "DevOps",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-2"],
    description: "Container orchestration",
    totalProgress: 0,
  },
  {
    id: "do-5",
    title: "AWS Cloud Fundamentals",
    category: "DevOps",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-1"],
    recommendedScore: 88,
    recommendationReason: "Deploy to the cloud! AWS skills are essential for modern infrastructure.",
    unlockedCourseIds: ["do-6", "do-9"],
    description: "Cloud infrastructure basics",
    totalProgress: 0,
  },
  {
    id: "do-6",
    title: "Infrastructure as Code",
    category: "DevOps",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-3"],
    description: "Terraform and automation",
    totalProgress: 0,
  },
  {
    id: "do-7",
    title: "Monitoring & Observability",
    category: "DevOps",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-2"],
    recommendedScore: 83,
    recommendationReason: "Keep your systems healthy! Learn monitoring, logging, and observability best practices.",
    unlockedCourseIds: ["do-9", "be-9"],
    description: "Track system health",
    totalProgress: 0,
  },
  {
    id: "do-8",
    title: "Linux System Administration",
    category: "DevOps",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: [],
    recommendedScore: 75,
    recommendationReason: "Foundation for DevOps! Master Linux to manage servers and troubleshoot issues.",
    unlockedCourseIds: ["do-2", "do-3"],
    description: "Master Linux operations",
    totalProgress: 0,
  },
  {
    id: "do-9",
    title: "Security & Compliance",
    category: "DevOps",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["do-5"],
    recommendedScore: 87,
    recommendationReason: "Secure your cloud infrastructure with security best practices and compliance standards.",
    unlockedCourseIds: ["be-6"],
    description: "Secure your infrastructure",
    totalProgress: 0,
  },

  {
    id: "ds-1",
    title: "Python Programming",
    category: "Data Science",
    status: "completed",
    sessions: generateSessions(9, "completed"),
    performance: { accuracyPct: 94, pace: 8.1, totalTasksCompleted: 102, totalTasksAttempted: 108 },
    prereqIds: [],
    description: "Python fundamentals",
    totalProgress: 100,
  },
  {
    id: "ds-2",
    title: "Data Analysis with Pandas",
    category: "Data Science",
    status: "completed",
    sessions: generateSessions(7, "completed"),
    performance: { accuracyPct: 89, pace: 7.4, totalTasksCompleted: 76, totalTasksAttempted: 85 },
    prereqIds: ["ds-1"],
    description: "Data manipulation and analysis",
    totalProgress: 100,
  },
  {
    id: "ds-3",
    title: "Data Visualization",
    category: "Data Science",
    status: "ongoing",
    sessions: generateSessions(3, "ongoing"),
    performance: { accuracyPct: 91, pace: 7.6, totalTasksCompleted: 24, totalTasksAttempted: 26 },
    prereqIds: ["ds-2"],
    description: "Create compelling visualizations",
    totalProgress: 38,
  },
  {
    id: "ds-4",
    title: "Machine Learning Basics",
    category: "Data Science",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-2"],
    recommendedScore: 93,
    recommendationReason: "You've mastered Pandas! Dive into ML algorithms and predictive modeling.",
    unlockedCourseIds: ["ds-5", "ds-6"],
    description: "Introduction to ML algorithms",
    totalProgress: 0,
  },
  {
    id: "ds-5",
    title: "Deep Learning with TensorFlow",
    category: "Data Science",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-4"],
    description: "Neural networks and deep learning",
    totalProgress: 0,
  },
  {
    id: "ds-6",
    title: "Natural Language Processing",
    category: "Data Science",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-4"],
    description: "Text analysis and NLP",
    totalProgress: 0,
  },
  {
    id: "ds-7",
    title: "SQL for Data Analysis",
    category: "Data Science",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-1"],
    recommendedScore: 91,
    recommendationReason: "Essential skill! Query databases efficiently for data analysis and reporting.",
    unlockedCourseIds: ["be-3", "ds-9"],
    description: "Query and analyze databases",
    totalProgress: 0,
  },
  {
    id: "ds-8",
    title: "Statistics for Data Science",
    category: "Data Science",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-2"],
    recommendedScore: 89,
    recommendationReason: "Build a strong foundation! Statistics is crucial for data-driven decision making.",
    unlockedCourseIds: ["ds-4"],
    description: "Statistical analysis fundamentals",
    totalProgress: 0,
  },
  {
    id: "ds-9",
    title: "Big Data with Spark",
    category: "Data Science",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["ds-2"],
    recommendedScore: 73,
    recommendationReason: "Scale your data processing! Handle massive datasets with distributed computing.",
    unlockedCourseIds: ["be-4"],
    description: "Process large-scale data",
    totalProgress: 0,
  },

  {
    id: "mb-1",
    title: "React Native Basics",
    category: "Mobile",
    status: "completed",
    sessions: generateSessions(8, "completed"),
    performance: { accuracyPct: 90, pace: 7.5, totalTasksCompleted: 92, totalTasksAttempted: 102 },
    prereqIds: ["fe-3"],
    description: "Cross-platform mobile development",
    totalProgress: 100,
  },
  {
    id: "mb-2",
    title: "Mobile UI/UX Design",
    category: "Mobile",
    status: "ongoing",
    sessions: generateSessions(5, "ongoing"),
    performance: { accuracyPct: 88, pace: 7.0, totalTasksCompleted: 34, totalTasksAttempted: 39 },
    prereqIds: ["mb-1"],
    description: "Design mobile experiences",
    totalProgress: 52,
  },
  {
    id: "mb-3",
    title: "iOS Development (Swift)",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: [],
    recommendedScore: 82,
    recommendationReason: "Expand to native iOS! Build high-performance apps for Apple ecosystem.",
    unlockedCourseIds: ["mb-6", "mb-9"],
    description: "Native iOS apps",
    totalProgress: 0,
  },
  {
    id: "mb-4",
    title: "Android Development (Kotlin)",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: [],
    recommendedScore: 80,
    recommendationReason: "Reach billions of users! Learn native Android development with modern Kotlin.",
    unlockedCourseIds: ["mb-6", "mb-9"],
    description: "Native Android apps",
    totalProgress: 0,
  },
  {
    id: "mb-5",
    title: "Flutter Development",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: [],
    recommendedScore: 86,
    recommendationReason: "Build for iOS and Android with one codebase! Flutter is fast and beautiful.",
    unlockedCourseIds: ["mb-6", "mb-7"],
    description: "Build with Flutter/Dart",
    totalProgress: 0,
  },
  {
    id: "mb-6",
    title: "Mobile App Performance",
    category: "Mobile",
    status: "locked",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["mb-1"],
    description: "Optimize mobile apps",
    totalProgress: 0,
  },
  {
    id: "mb-7",
    title: "Mobile Testing & QA",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["mb-1"],
    recommendedScore: 84,
    recommendationReason: "Ship with confidence! Learn mobile testing strategies and automation.",
    unlockedCourseIds: ["mb-9"],
    description: "Test mobile applications",
    totalProgress: 0,
  },
  {
    id: "mb-8",
    title: "Push Notifications & Analytics",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["mb-1"],
    recommendedScore: 76,
    recommendationReason: "Engage and retain users with push notifications and analytics insights.",
    unlockedCourseIds: ["mb-9"],
    description: "Engage users effectively",
    totalProgress: 0,
  },
  {
    id: "mb-9",
    title: "App Store Deployment",
    category: "Mobile",
    status: "recommended",
    sessions: [],
    performance: { accuracyPct: 0, pace: 0, totalTasksCompleted: 0, totalTasksAttempted: 0 },
    prereqIds: ["mb-1"],
    recommendedScore: 71,
    recommendationReason: "Ready to launch! Learn the process of publishing to App Store and Google Play.",
    unlockedCourseIds: [],
    description: "Publish to app stores",
    totalProgress: 0,
  },
]
